### ISSUE TITLE
Quality of score / suggestions / warnings

### ISSUE THREAD

**Issue by oskar-gmerek** [zxcvbn-ts/zxcvbn#109]
Hi,

I was testing my implementation and found out something strange.

Password: **johnwick1233**
Score: **4 / 4**
guess times (10  / second): **centuries**
match sequence: **[passwords, lastname, date]**
Suggestions: **no suggestions**
Warning: **no warnings**
**Same password reduced by last character is pwned as well** (johnwick123)

Password: **johnwick2022**
Score: **3 / 4**
guess times (10  / second): **1 year**
match sequence: **[passwords, lastname, recentYear]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **johnwick2030**
Score: **4 / 4**
guess times (10  / second): **centuries**
match sequence: **[passwords, bruteforce]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **fuckputin2022**
Score: **3 / 4**
guess times (10  / second): **10 months**
match sequence: **[passwords, wikipedia, recentYear]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **johndoe1233**
Score: **3 / 4**
guess times (10  / second): **4 months**
match sequence: **[passwords, date]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **sunnyflower12**
Score: **3 / 4**
guess times (10  / second): **4 months**
match sequence: **[passwords, passwords]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **sunnyflower12**
Score: **3 / 4**
guess times (10  / second): **4 months**
match sequence: **[passwords, passwords]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **sun.flower123**
Score: **3 / 4**
guess times (10  / second): **2 years**
match sequence: **[bruteforce, passwords, sequence]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **john@gmail.co**
Score: **4 / 4**
guess times (10  / second): **centuries**
match sequence: **[bruteforce, passwords]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **john@netflix**
Score: **3 / 4**
guess times (10  / second): **4 months**
match sequence: **[firstnames, wikipedia]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **example@gmail**
Score: **3 / 4**
guess times (10  / second): **1 year**
match sequence: **[bruteforce, wikipedia, commonWords]**
Suggestions: **no suggestions**
Warning: **no warnings**

Password: **mark&olivia**
Score: **3 / 4**
guess times (10  / second): **5 months**
match sequence: **[passwords, bruteforce, passwords]**
Suggestions: **no suggestions**
Warning: **no warnings**

I think all of above passwords are weak, if not very weak. 
I think the score is much too high for that kind of passwords.
I think that warnings and/or suggestions should show up for all of them.

The most important here is scoring, score 4/4 suggesting that password is at least great.
"**johnwick2030**" got 4/4, but max score should get password like "**f6376c03-4#0D78-11c7@35d94-79a3df2#314Fd63@s73GgM!!**"
I guessing that most of developers using zxcvbn-ts in their software are using scoring to give feedback to users how strong or weak are they passwords. If they give the same feedback for both above passwords, that is nearly clear that user will think that passwords are both great. But they are not strong on the same level, not even close for first one to second one.

Im thinking that score scale should be 0/10. All of the above password should left at 3/10 or 4/10. 
Additional password score should be based on length, number of special characters, number of numbers, number of sequences (and avg length of sequences).
I think that scoring 7/10 and above should be impossible for passwords which can be remembered by human. That will show to users that they no need a great password to be secure, but if they use a best password managers to generate 10/10 password for them, they can be sure that they do everything what they can do if is about of creating passwords.

I guessing that changing scale of score, and adding additional points for passwords based on their length, used special characters, numbers etc should be not that hard to do (but I just guessing) and after that library will benefit a lot.

@MrWook What do you think? Is that even possible?

**Comment by MrWook** [comment]
Hey thanks for the comment!

i see why you think that a pwned password with only one more character is weird to jump from 0 to a 4 but the problem is you can't use the levenstein distance with the Have I Been Pwned api because the passwords are encrypted and you only check against this encryption and not the real password.

I get why you think those passwords seem to be "weak" but a password isn't strong just because they have a special character, a number, an uppercase letter etc. For example P4$$w0rd has everything it needs but its worthless
This library takes some attack pattern from hackers and formed it into a scoring.

One could change the scoring to 1-10 instead of 0-4 but it wouldn't change the outcome because `johnwick2030` would still have the same guess count which is the base of the scoring.
From the code:
```
    const DELTA = 5
    if (guesses < 1e3 + DELTA) {
      // risky password: "too guessable"
      return 0
    }
    if (guesses < 1e6 + DELTA) {
      // modest protection from throttled online attacks: "very guessable"
      return 1
    }
    if (guesses < 1e8 + DELTA) {
      // modest protection from unthrottled online attacks: "somewhat guessable"
      return 2
    }
    if (guesses < 1e10 + DELTA) {
      // modest protection from offline attacks: "safely unguessable"
      // assuming a salted, slow hash function like bcrypt, scrypt, PBKDF2, argon, etc
      return 3
    }
    // strong protection from offline attacks under same scenario: "very unguessable"
    return 4
```
This means if we would change the scoring we would add more if statements between and at the beginning. Of course one could say that the hardware is getting better and better which means 1e10 isn't nearly as good as 2012 when the code was written but that is something else.
Every password can be cracked over time so the only scoreable value is the guess count. Just because a human can remember the password doesn't mean its a bad one. For example if you use a whole sentence its a good password too.
Feel free to checkout the talk from Daniel Lowe Wheeler the original author of zxcvbn https://www.usenix.org/conference/usenixsecurity16/technical-sessions/presentation/wheeler it has a good explanation about this topic.

So i think the scoring change wouldn't change a thing so thats a no on my site. 
Adding matchers for "passwords based on their length, used special characters, numbers etc" it's a no from my site too because that is a very old paradigm that doesn't really fit in our time as you can see in the presentation.
BUT that just means that i won't add them to the core library. Feel free to create you own custom matcher and score it as you seem to be right.
We already had a discussion for it in here https://github.com/zxcvbn-ts/zxcvbn/discussions/15 
So i added custom matcher. In the documentation is an example for a minLength matcher https://zxcvbn-ts.github.io/zxcvbn/guide/matcher/#custom

**Comment by MrWook** [comment]
I will close this issue for now because of inactivity. If there are other question please open a discussion
