### ISSUE TITLE
fastest-levenshtein error on a ESM project

### ISSUE THREAD

**Issue by RoXuS** [zxcvbn-ts/zxcvbn#121]
hey, we get the following error on esm projet, there is a fix?

<img width="565" alt="image" src="https://user-images.githubusercontent.com/3296671/177638289-fa29ce21-fd6b-4035-96b9-5e329313223b.png">

**Comment by RoXuS** [comment]
Yes: https://github.com/RoXuS/test-zxcvbn

You can launch this project then launch `yarn` and `yarn start`.
You will get the error when you go on http://localhost:8000.

The error come because `fastest-levenshtein` is not esm compatible, there build create only a "commonjs" package.

**Comment by MrWook** [comment]
Hm i would assume the problem lies within the @web/dev server. Never had any problems with webpack, rollup or esm 🤔 But i guess i never went full esm with it like you did.

I would say we wait a few days for your PR https://github.com/ka-weihe/fastest-levenshtein/pull/18 and if it is not merged i will copy paste the code into zxcvbn-ts

**Comment by MrWook** [comment]
I copied it into this repo. So it should work now in your setup

**Comment by RoXuS** [comment]
works like a charm!

Thx!
