### ISSUE TITLE
Change return value of feedback.warning when there is no warning given

### ISSUE THREAD

**Issue by U-4-E-A** [zxcvbn-ts/zxcvbn#148]
Currently returns the following if no warning found: -

`feedback: { warning: '', suggestions: [] }`

Suggest changing type of warning to `string | null` or `string[]`

Reason - empty string still indicates on a programmatic level that a warning "exists". Even though the warning is not currently an array (rather a single string), a return of `warning: []` or `warning: ["A warning message here"]` may be a logical option. 

If a string (rather than an array of strings) is to be returned, suggest `warning: null` or `warning: "A warning message here"` to establish non-existence of warning. This will allow for `if(feedback.warning) {...}` rather than `if(feedback.warning.length) {...}`, which is somewhat hackish.

**Comment by MrWook** [comment]
I don't really understand this.
An empty string is a falsy value so `if(feedback.warning)` should work fine 🤔 
Additional there will always be only one warning because this is something set by the highest matcher and are not combined same with the suggestions.

**Comment by bagbag** [comment]
> An empty string is a falsy value so `if(feedback.warning)` should work fine

While it does work, it relies on JavaScripts coercing, which is simply not clean, at least in my view.
Image that you forget to check with an if, then it will just proceed with that empty string. If you have null instead, the TypeScript compiler will complain.

**Comment by MrWook** [comment]
It was your improved example with `if(feedback.warning)`, which is ignoring an empty warning just fine.

What is the use case where a typescript compile will throw an error?

**Comment by bagbag** [comment]
I found this library yesterday and added it to my code. I already have other stuff there which is why I mix the results (code simplified):

```ts
type CheckPasswordResult = {
  warnings: string[]
};

function examplePasswordCheck(password: string): CheckPasswordResult {
  const zxcvbnResult = zxcvbn(password);
  const someOtherResult = someOtherStuff(password);

  const warnings: string[] = [zxcvbnResult.feedback.warning, ...someOtherResult.warnings];
  return { warnings };
}

function consumer(): void {
  const passwordResult = examplePasswordCheck('password-from-request');

  if (passwordResult.warnings.length > 0) {
    throw new Error('Bad password.');
  }

  doSomethingWithThePassword();
}
```

As I always work with `null`/`undefined` instead of an empty string, this was what I did intuitively. There will be no compiler error from TypeScript. So I run the code... and what I get is an unwanted runtime behavior, even though I check the length of the array. Now I have to take some time and debug what happens.

Now imagine it would return `null` instead of `''`. TypeScript would complain that `null` is not allowed inside of that `string[]` and I could see instantly what the problem is.

With just `string` it is ambiguous, while `string | null` is unambiguous.

**Comment by MrWook** [comment]
That use case seems more than reasonable 👍 

Will change it to null, which would be a breaking change but good thing i'm currently developing against a new major version anyway

**Comment by U-4-E-A** [comment]
Victory!

Can I ask what changes we will see in the new major version?

**Comment by MrWook** [comment]
Apart from this change, it will be everything since the MR #174 
Which means:
- language packages treeshakeable
- removal of default exports
- networkError handler options for the pwned matcher
- diceware dictionary with separated scoring for the dictionary matcher
- a compound splitter which is used by the generator of the dictionaries => smaller bundle size for the spanish package

Additionally i'm trying to work on a "unmunger" instead of the l33t speak to search for more complex l33t speak stuff. If i don't get this done i can at least fix https://github.com/zxcvbn-ts/zxcvbn/issues/118 which is kind of breaking.

Another thing that i'm working on is trying to fix the ReDOS vulnerability https://github.com/dropbox/zxcvbn/issues/327

It would be nice if i could land the seperator MR too https://github.com/zxcvbn-ts/zxcvbn/pull/115

**Comment by Tostino** [comment]
@MrWook I have a new PR for implementing an "unmunger" if you want to look through it: https://github.com/GoSimpleLLC/nbvcxz/pull/84

I haven't had a chance to look through it to merge yet, but wanted to bring it to your attention.
