### ISSUE TITLE
Internationalization of Matcher feedback

### ISSUE THREAD

**Issue by gabberr** [zxcvbn-ts/zxcvbn#159]
The DefaultFeedbackFunction of the Matcher returns a string.
```js
  feedback() {
    return {
      warning: `Password length should exactly 69`,
      suggestions: [],
    }
  },
```
The issue is when the locale is known only at runtime, and we would like to show a diffrent message. For example, the user uses the german locale 'de_DE'.

What would be the best approach here?

**Comment by MrWook** [comment]
The default string for every matcher is a key. For example if you don't add any translation the regex matcher will give you 
```
{
      warning: `recentYears`,
      suggestions: ['recentYears', 'associatedYears'],
}
```
If you have a translation library you can use this to translate the keys.

For example i'm using a lot of vue and there is the translation library vue-i18n. With the keys above i would translate them with `i18n.t('zxcvbn.warning.${result.warning}')`.

If you check out the regex feedback function [here](https://github.com/zxcvbn-ts/zxcvbn/blob/master/packages/libraries/main/src/matcher/regex/feedback.ts). You can see that it is simply using the translations from the zxcvbnOptions.


I think if you want to have per user translations you need to have a translation library and use keys. On the other hand you could always update the zxcvbnOptions per user if you have this on the client.

**Comment by gabberr** [comment]
Thank you, the solution of using `feedback.warning` as a translation key and doing the translations outside solved our problem. 👍 

Just some thoughts:

> The default string for every matcher is a key

This is don't quite get. A custom matcher has to implement `feedback` method, and `warning` property of the return object is not optional.  

If I could skip implementation of `feedback`, then it would work return this?
```js
{
   warning: `<matcher name>`,
   suggestions: [],
}
```
The <matcher name> can be then used for the translation key. Now I have to explicitly return it.

**Comment by MrWook** [comment]
I think I have expressed myself incorrectly. 
Any current built-in matcher of zxcvbn-ts in this repository works as described above. 
It's doing it by using for example `zxcvbnOptions.translations.warnings.recentYears`. And the default values for the translation objects are the keys which can be overwritten with the language packages.

Adding a default feedback function which just adds the Matcher name as a key would be confusing because if a user is adding a matcher without a feedback function and it would add a key but the user has set the translation options. I'm pretty sure the user would forget that this matcher is missing a translation.
So i think it alway should be set explicit.

**Comment by MrWook** [comment]
This seems to be answered so i will close this issue
