### ISSUE TITLE
Possible to only use translation?

### ISSUE THREAD

**Issue by lekoaf** [zxcvbn-ts/zxcvbn#175]
I'm not interested in using the dictionaries, because of size limitations.
I am however interested in the translations, because that's one thing the original library was missing.

However, it doesn't seem like it's possible to _just_ import the translations?

![2023-02-06_13-40](https://user-images.githubusercontent.com/7765599/216974379-bd19e0c9-7067-4133-852e-ba43e63baaa1.png)

Would that mean there is no way to tree shake away the dictionary?

**Comment by MrWook** [comment]
True this is kind of annoying. The export should look like this:
```
export { 
 dictionary,
 translation
};
```
I think i will adjust this but in the meantime you could just import the translations directly:
```
import translations from '@zxcvbn-ts/language-en/dist/translations'
```

**Comment by lekoaf** [comment]
Good tip! I'll see if I can work with that.

**Comment by MrWook** [comment]
This will be a major release and i want to have a few more thing in it so i won't immediately create a new major release.
I don't know when i find the time to add the things I want to have in the next major release.
But the topic here is not really a blocker, because you can easily bypass it with the direct import
