### ISSUE TITLE
Guesses value is higher than it should be when the l33t matcher uses a replacement of multiple symbols to one

### ISSUE THREAD

**Issue by zeezooz** [zxcvbn-ts/zxcvbn#205]
The l33t matcher matches the clean password instead of the original one, so it consumes only a portion and the rest is consumed by another matcher which leads to erroneous increase of guesses.

For example, "#ome" and "|-|ome" both are equivalents of "home".
The l33t matcher matches "#ome" entirely, so it produces 1 match (l33t).
But for "|-|ome" it matches only "|-|o", so "me" is matched by another matcher and it produces 2 matches (l33t + dictionary) with much higher guesses.

The related test:
https://github.com/zxcvbn-ts/zxcvbn/blob/adb801e6be453f44b33dbd1606ceca4283312d59/packages/libraries/main/test/matcher/dictionary/variant/matching/l33t.spec.ts#L112-L117
should be
```
        '(()mp|_|ter',
        '(()mp|_|ter',
        'computer',
        'words',
        5,
        [0, 10],
```

**Comment by MrWook** [comment]
I see, i guess this is because the length of the password is not adjusted to the cleaned password. 
So if we have `|-|ome` it will match to `home` and it will use the token `|-|o` as it is 4 characters long like home.
Now the last two characters are still in pool of possible matches so it will use another matcher for it.

So if we have a multi symbol substitution we need to increase the length of the token. which is the parameter `j` in the sequence to match the correct password string.
This could break other stuff 🤔  I will look into it.

Thanks for this bug report! 👍
