### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by henrywoody** [zxcvbn-ts/zxcvbn#31]
I've set up an app with `zxcvbn-ts` to show password strength and offer suggestions to the user. Nothing special, the options are exactly as show in the docs. Also want to say `zxcvbn` is a great project and I appreciate the work you're doing to keep it going.

I've noticed, though, that `zxcvbn-ts` is not fast enough to run on each keypress (value update in React). When rendering the password strength component with `zxcvbn-ts`, there is noticeable lag while typing (especially when typing as fast as possible as a stress test). The base `zxcvbn` package, on the other hand, is able to calculate password strength on keypress without any noticeable delay.

Is there any way to improve performance when using this package?

I've seen this line in the README: "usable without dictionaries at all, which reduce the scoring efficiency rapidly." (I'm assuming it means reduce the scoring _time_ or _increase_ efficiency), however it's followed by "This is not recommended."

Happy to help out with this project too if you can point me in the direction of areas that might be affecting performance.

For reference here are my options:

```typescript
const zxcvbnOptions = {
    dictionary: {
        ...zxcvbnCommonPackage.dictionary,
        ...zxcvbnEnPackage.dictionary,
    },
    translations: zxcvbnEnPackage.translations,
};
```

**Comment by MrWook** [comment]
Hey, thanks for the report i tried it on the demo page it was a little laggy for me too if i tried to type as fast as i can with random keys.

I guess it's because we always set those HUGE dictionaries every time we type something.
I build an Options Singleton which handles the zxcvbn options. This means we could separate the options handling from the typing. This should be in the examples, i guess
Basically what I mean is something like that, which you can already test by yourself:

```
import zxcvbn from '@zxcvbn-ts/core'
import ZxcvbnOptions from '@zxcvbn-ts/core/Options'
import zxcvbnCommonPackage from '@zxcvbn-ts/language-common'
import zxcvbnEnPackage from '@zxcvbn-ts/language-en'

// Set the options somewhere else for example on page load or after lazyloading the dictionaries 
ZxcvbnOptions.setOptions({
  dictionary: {
    ...zxcvbnCommonPackage.dictionary,
    ...zxcvbnEnPackage.dictionary,
  },
  translations: zxcvbnEnPackage.translations,
})

// only use the value for the zxcvbn call in the type handler
function typeHandler(value) {
  return zxcvbn(value)
}
```

On my local machine for the demo page this got rid of the small lags on fast typing till a certain password length.
Do you mind testing this on your end, too?

**Comment by MrWook** [comment]
Ah and by the way.
With `which reduce the scoring efficiency rapidly.` i meant that the scoring will loos its significance without dictionaries-

**Comment by henrywoody** [comment]
Hey MrWook, thanks for the response. That looks like it should be the solution however I've come into a couple issues with this.

First I'm not able to import `'@zxcvbn-ts/core/Options'` as you show. I encounter `Error: Can't resolve '@zxcvbn-ts/core/Options'`.

I can import using `'@zxcvbn-ts/core/dist/Options'` without error, but this approach definitely does not set the dictionaries correctly (e.g. "password123" receives a score of 4/4).

I think including a named export of `Options` in the main `index.ts` could resolve this.

Can you test things out in an external package that imports `@zxcvbn-ts/zxcvbn`?

**Comment by MrWook** [comment]
I'm sry about the confusion with the `dist` folder didn't thought about that.

I tested it in a separated environment where i imported it with the package from npm. Something to keep in mind, that the Options file is a singleton which means you need to use the same filetype as the default import from the core.
You probably using webpack or another bundler if you are using react, which means that the esm packages is used.
Can you check out if there are improvements with the correct score if you use `@zxcvbn-ts/core/dist/Options.esm`

**Comment by MrWook** [comment]
The fix is published with the newest version `0.3.0`

**Comment by oliviercperrier** [comment]
@MrWook I get this with the version 3.0.2. 

It super slow, some password need more than 3 secondes to compute strength.

**Comment by MrWook** [comment]
@oliviercperrier are the passwords that you typed slow on the demo page too? https://zxcvbn-ts.github.io/zxcvbn/demo/

**Comment by oliviercperrier** [comment]
> @oliviercperrier are the passwords that you typed slow on the demo page too? https://zxcvbn-ts.github.io/zxcvbn/demo/

@MrWook Yes, i use the orignal lib fron dropbox with all dictionnaries and i get a calc time of like 40ms. But with zxcvbn-ts the calc timr with the same password is 2400ms..

**Comment by MrWook** [comment]
@oliviercperrier This is a weird question but could you give me an example password? Not the real password that you are trying, except if its just a test password than you can give it to me.

What you can try on the demo page is disable the pwned matcher and the levenshtein distance.
Both of them are new features which can take longer. The pwned matcher because it makes network request and the levenshtein distance gets slower for long passwords with a lot of special characters like `()"§=%&!*'_:§=$/"%§)"%§'*_:;+-*/=/*-+§$)§()/§"$'*_:;`

**Comment by BioSurienDG** [comment]
@MrWook Here is an example (see screenshot). It takes almost 4 seconds to get a result while the other lib is very fast
<img width="1062" alt="image" src="https://github.com/zxcvbn-ts/zxcvbn/assets/98058801/0e5248a3-3222-4ede-905f-08c9a7cf4654">
<img width="564" alt="image" src="https://github.com/zxcvbn-ts/zxcvbn/assets/98058801/c47fe916-726d-43be-a743-16c355b2c86e">

**Comment by BioSurienDG** [comment]
@MrWook Also, since there is a known example of this issue can we reopen the ticket? Also, any thoughts on when this may be fixed?

**Comment by BioConnor** [comment]
@MrWook It looks like it has to do with the `l33t` matcher. If the `l33tMaxSubstitutions`  option is set to 0, the above password calculation time ranges anywhere from ~200ms to ~70ms, as seen in the attached image. Is this a known issue?
![image](https://github.com/zxcvbn-ts/zxcvbn/assets/132945353/0e36962e-90fb-482b-a856-bb006a09ea16)

**Comment by ghaskins99** [comment]
fyi @MrWook I checked in Chrome's performance tools and it looks like it's (at least partially) the l33t matcher. Disabling (setting the `l33tMaxSubstitutions` to 0) on the demo page brings performance back; sometimes 70ms, sometimes ~230ms. Setting it to 100 is still slow.

(fyi also the default for l33tMaxSubs in [code appears to be 512](https://github.com/zxcvbn-ts/zxcvbn/blob/ce3aed62ab3e95ebf89cec0ece737eb8579149a9/packages/libraries/main/src/Options.ts#L40), but the docs say 100. Should it be 512 or 100?)

using `l33tMaxSubstitutions: 0` in the demo page:

![image](https://github.com/zxcvbn-ts/zxcvbn/assets/43185853/f9090eea-4c12-463b-8c30-8e05b0202571)

it also appears that the repeated `!!!` is part of the issue; I'm assuming since it's a possible-l33t character. using all alphanumeric characters with `l33tMax: 512` is still fast at 30ms, but add a few "l33t" characters (ex. `!`) and see the time spike:

<img width="710" alt="image" src="https://github.com/zxcvbn-ts/zxcvbn/assets/43185853/75e68bac-13fd-440e-905d-03b43809ef2d">

**Comment by MrWook** [comment]
@ghaskins99 @BioSurienDG let's move this into https://github.com/zxcvbn-ts/zxcvbn/issues/228 as this ticket is about the options handling
