### ISSUE TITLE
How to use AZERTY in 0.3.0?

### ISSUE THREAD

**Issue by SimonBackx** [zxcvbn-ts/zxcvbn#61]
In the changelog it is noted that AZERTY support is added in 0.3.0, but this is not yet reflected in the documentation (which is for 1.0.0 beta, I think). How do you enable it?

In the documentation:

> By default zxcvbn-ts don't use any keyboard patterns to let the developer decided how much of the library will be used. It is recommended to use at least the common keyboard patterns.

But there is no documentation on how to enable this (and more specifically to enable only AZERTY). And there are no adjacencyGraphs available in 0.3.0:

Type definition of `@zxcvbn-ts/language-common`:

```ts
declare const _default: {
    dictionary: {
        userInputs: string[];
        passwords: string[];
    };
    // <- no adjacencyGraphs as stated in the documentation
};
export default _default;
```

**Comment by MrWook** [comment]
Hey,
in 0.3.0 the `adjacencyGraphs ` are all active by default, this changed in 1.0.0 so that the developer can decided which graphs to use. Here is documentation from 0.3.0  https://github.com/zxcvbn-ts/zxcvbn/tree/%40zxcvbn-ts/core%400.3.0/docs/guide/options

Btw. the 1.0.0-beta version is working just fine, i just wanted to add all bigger api changed into it before releasing a real 1.0.0.

**Comment by SimonBackx** [comment]
Ah okay, I get it! Thanks! The beta tag was a bit scary to use in development ;) So I'll wait for the API to settle a bit before using it in production.
