### ISSUE TITLE
Diceware testing

### ISSUE THREAD

**Issue by depperm** [zxcvbn-ts/zxcvbn#88]
It seems [diceware ](https://diceware.dmuth.org) passwords are often considered good with zxcvbn (I really like both zxcvbn and diceware). However as pointed out on this [security exchange answer](https://security.stackexchange.com/questions/208937/is-diceware-more-secure-than-a-long-passphrase) technically diceware without user modification have a dictionary size of 8000 so the randomness for `8000 words is 8000^3= 512 billion possible phrases`. So even though the passphrase maybe 'TurkeyGlanceUnbiased' gets a good zxcvbn rating, its basically the same as 'abc'.

Should zxcvbn measure against known diceware dictionaries?

**Comment by MrWook** [comment]
I don't really get why `TurkeyGlanceUnbiased ` is a bad thing. In the security exchange answer there is a sentence after the 512 billion possible phrases:
> So an attacker, when guessing the phrase, would have to try 256 billion phrases (on average) before s/he gets it right

256 billion guesses would be scored by zxcvbn as a 4, which means the maximum.
I'm all in for more dictionaries or new matchers but i don't see that we could just throw a diceware dictionary in here. The diceware dictionaries are just lists of easy to remember word in a random order. 
We wouldn't get anything from it to match them with anything.

The answer already described the problem with diceware which can't be solved with zxcvbn. 
The problem lies in the Person or the dictionary that is used. If the person is using a regular sentence like `Long life Typescript` its as bad as using a diceware dictionary with only 1000 entries.

Just my opionion but `TurkeyGlanceUnbiased` isn't as bad as `abc`. How should the hacker know that you are using a diceware dictionary. Most of the time those guys are going through rainbowtables or social hacking. Maybe some bruteforce. Even if the hacker knows that you are using this specific diceware table with 8000 words in it he would need to  try 256 Billion times to get it right on average.

zxcvbn gives you some more information on the guess time for `TurkeyGlanceUnbiased` it is this:
```
100 / hour: | centuries | (throttled online attack)
10  / second: | centuries | (unthrottled online attack)
10k / second: | centuries | (offline attack, slow hash, many cores)
10B / second: | 13 hours | (offline attack, fast hash, many cores)
```
Both online attacks are for cases if the hacker tries to access your account directly over the login page. Which can be slowed down massivly if you throttle the login requests.
The offline attacks are for cases if the hacker has access to the database with hashed values.. Which can be slowed down massively if you use a slow hash algorythm.

At the end the developer of the application is responsible for how fast a hacker can get the passwords and `256 billion guesses` are pretty high for it.

**Comment by depperm** [comment]
My thought was most password hacks aren't from going to a site and attempting x number of logins, but from password dumps and comparing hashes. I've seen diceware lauded multiple places about randomness, but the dictionaries are also known. So if a nefarious person has a password dump and wants to figure out passwords. Instead of guessing `aaa`, `aab`, `aac`, `aad`.... which would mean `TurkeyGlanceUnbiased` is really random. If they instead use a known diceware dictionary it could look like `AppleBananaOrange`, `AppleBananaGlance`, .... and it would be much easier to figure out.

While I agree `TurkeyGlanceUnbiased` is better than `abc` technically its only 8000^3 (this is better than 52^3), it is not 52^21 (unless user edits the phrase in some manner) which I believe zxcvbn uses (or something close)

The next sentences from the post point out:

>To compare with a password of similar strength: a random password using 7 characters, consisting of a-z and A-Z, has a "dictionary size" of 52 (26 + 26) and a "number of words" of 7, making 52^7= ~1028 billion possible passwords. It is well-known that 7 characters is pretty insecure, even when randomly generated.

My point is that I see a potential for password cracking using diceware in the future as technically you can cover quite a bit of long passwords with a smaller dictionary. I'm not super in the know of security, but looking at the numbers it seems diceware passphrases (if unedited) would open up password cracking.

**Comment by Tostino** [comment]
@depperm The whole point of diceware is that the dictionary is expected to be "known" while still providing the security expected. Essentially, if the word doesn't exist in any of the dictionaries, then it'll get treated as a brute force match, which would artificially increase the entropy. In practice, I have not seen that happen.

**Comment by depperm** [comment]
@Tostino not sure exactly what your point is. Are you saying brute force password crackers just use a generic dictionary of single words and so diceware is secure?

**Comment by Tostino** [comment]
No, I am saying the way they calculate the theoretical entropy of a Diceware generated password is assuming that the attacker knows the exact dictionary that was used to generate it.

**Comment by depperm** [comment]
@Tostino my comment is about zxcvbn estimation not diceware

**Comment by Tostino** [comment]
So are you actually seeing misestimation? Here is your example run through nbvcxz (the library I maintain):

![image](https://user-images.githubusercontent.com/8227578/152386931-8f6e2c2e-da90-49c1-bf9c-ca1a4490089c.png)


Each word in a diceware generated password is 12.9 bits of entropy. So a three word password should be 38.7 bits.

**Comment by depperm** [comment]
I'm seeing `TurkeyGlanceUnbiased` getting a 4/4 score on https://zxcvbn-ts.github.io/zxcvbn/demo/ and something like `J8er23i` only getting 2/4. Randomness for `J8er23i` should actually be about double of the the diceware, I believe (52^7 > 8000^3).  What I'm saying is there is a potential to think longer inherently implies more secure, but if relying on a known password creation engine, I feel like actual entropy is lower.

**Comment by MrWook** [comment]
@Tostino the original js library and this typescript port don't have a `eff_large` dictionary. We only have ranked dictionaries.
This would be a bigger difference between our libraries but in this case it doesn't really matter. Thanks again for all this clarification ❤️ 

@depperm So you just want some common diceware dictionaries in this library and if a word is in this dictionary it will get a lower score for example we have `Turkey` which has a guess count of `1742`.
Now if this word in in a diceware dictionary the guess count will drop by a set amount? For example divided by 2 or so 🤷 Just as an example. 

Is my assumption correct?

**Comment by depperm** [comment]
@MrWook something like that. I don't know how much it should lower the score, just that IMO the theory is that a 3 phrase diceware be about equal to(or less than) a 6 letter word. Again I use zxcvbn and diceware, both are great implementations, I just don't think zxcvbn has considered testing diceware phrases.

**Comment by MrWook** [comment]
Do you have some diceware dictionary sources that could be used?

**Comment by depperm** [comment]
[EFF](https://theworld.com/~reinhold/diceware.wordlist.asc), [Beale](https://theworld.com/~reinhold/beale.wordlist.asc), [Diceware](https://github.com/dmuth/diceware/blob/main/wordlist/wordlist-5-dice-eff.js)

**Comment by Tostino** [comment]
@MrWook That explains it. That was the whole reason I implemented the "unranked" dictionary concept in Nbvcxz. Sorry, my memory on this is a little fuzzy after a number of years. I decided to only include the one eff_large dictionary with Nbvcxz at the time. I didn't remember that wasn't a thing in the original implementation.

If you include the words that are common between all diceware dictionaries into a single one, but give each word the same rank (3888) that should score them properly, even if the dictionary we are using has more than 7776 words in it.

**Comment by MrWook** [comment]
Seems reasonable, but those lists have more than 100k entries together. I would merge them and clean them up a little bit. The first two are pretty even and i guess i would only use words with >= 4 characters otherwise there would be too many false positives.

@Tostino if i'm correct you are only using the [Diceware](https://github.com/dmuth/diceware/blob/main/wordlist/wordlist-5-dice-eff.js) dictionary for Nbvcxz?

**Comment by strider72** [comment]
I'm pretty sure that three words is not considered secure in Diceware. You need at least five -- or even six -- words to even begin to resist a brute force attach on a hash

**Comment by depperm** [comment]
@strider72 that's basically the point. zxcvbn thinks a ~15 length password is good, but if this password is based on diceware it isn't
